supported_languages:
  - de
default_score_threshold: 0.4

recognizer_registry:
  supported_languages:
    - de
  global_regex_flags: 26
  recognizers:
    - name: CreditCardRecognizer
      type: predefined
      supported_languages:
        - language: de
          context: [kreditkarte, karte, zahlkarte, visa, mastercard, amex]

    - name: EmailRecognizer
      type: predefined
      supported_languages:
        - language: de
          context: [email, e-mail, mail, kontaktadresse]

    - name: IbanRecognizer
      type: predefined
      supported_languages:
        - language: de
          context: [iban, konto, bankverbindung, bankkonto]

    - name: IpRecognizer
      type: predefined
      supported_languages:
        - language: de
          context: [ip, ip-adresse, server]

    - name: PhoneRecognizer
      type: predefined
      supported_languages:
        - language: de
          context: [telefon, telefonnummer, handy, mobil, rufnummer]

    - name: SpacyRecognizer
      type: predefined
      supported_languages:
        - language: de

nlp_configuration:
  nlp_engine_name: spacy
  models:
    - lang_code: de
      model_name: de_core_news_md
